name: yolo3
dependencies:
  - python=3.6
  - libopencv=3.4.1
  - opencv=3.4.1
  - py-opencv=3.4.1
  - jupyterlab
  - pip:
    - tensorflow==1.13.1
    - keras==2.2.4
    - opencv-python==4.1.1.26
    - Pillow==6.2.1
    - matplotlib==3.1.1
    - configparser
    - imgaug